### ISSUE TITLE
Retrieving service logs

### ISSUE THREAD

**Issue by stevepeak** [asyncy/cli#100]
To help debug issues for a container the cli should retrieve specific service's logs like this:

```shell
asyncy logs <service>
```

The result would be effectively the same as calling `docker logs <containerid>` locally.

**Comment by judepereira** [comment]
Fixed with #106.

**Comment by judepereira** [comment]
To be able to retrieve all logs from all the services, you can run `asyncy logs --all`.

Filtering down the logs right now to logs from one service is not possible, due to the current logging architecture in asyncy. Specifically, we need to customise the Fluentd exporter to inject more tags and labels into each log entry to Stackdriver.
